name: TemplateMod
author: someAuthor
version: 0.1
main: com.addshore.TemplateMod

commands:
  test1:
    description: This is a test command.
    usage: /testcommand
    permission: test1.testcommand
    permission-message: You don't have testcommand
